### ISSUE TITLE
Blockly won't compile with typescript (at least v8.0.1)

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#6146]
**Describe the bug**

If you add Blockly to a typescript project, and attempt to type check it, it will not compile.

**To Reproduce**

See the steps in the [provided repository](https://github.com/johnnyoshika/blockly-typescript-libcheck).

**Expected behavior**

Blockly's type definitions should allow a project to compile.

**Stack Traces**

```
node_modules/blockly/blocks.d.ts:14:26 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.

14 import * as Blockly from './core';
                            ~~~~~~~~

node_modules/blockly/core.d.ts:14:13 - error TS2303: Circular definition of import alias 'Blockly'.

14 import * as Blockly from 'blockly';
               ~~~~~~~

node_modules/blockly/core.d.ts:14:26 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.

14 import * as Blockly from 'blockly';
                            ~~~~~~~~~

node_modules/blockly/index.d.ts:17:26 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.

17 import * as Blockly from './core';
                            ~~~~~~~~

node_modules/blockly/javascript.d.ts:14:26 - error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.

14 import * as Blockly from './core';
                            ~~~~~~~~


Found 5 errors in 4 files.

Errors  Files
     1  node_modules/blockly/blocks.d.ts:14
     2  node_modules/blockly/core.d.ts:14
     1  node_modules/blockly/index.d.ts:17
     1  node_modules/blockly/javascript.d.ts:14
```

**Additional context**

Reported by a lovely forum person [here](https://groups.google.com/d/msgid/blockly/e6803543-9b55-49e2-bf4e-e870076eb972n%40googlegroups.com).

Changed somewhere between v6 and v8.0.1

**Comment by maribethb** [comment]
Duplicate of https://github.com/google/blockly/issues/6079, please follow there for updates
